### PR TITLE
Remove the ui pattern definition

### PR DESCRIPTION
**Pull request by pookmish**
# READY FOR REVIEW

# Summary
- Fixed the pattern template override

# Review By (Date)
- ASAP

# Criticality
- 7

## Setup tasks and/or behavior to test

1. Check out this branch
2. rebuild caches
3. add a news list to a page.
4. verify you can still edit the page.

### CODE REVIEW

**Comment by pookmish** [comment]
Note, i removed a hard coded width (bad practice) that was causing container overflow. I didn't compile the css though.

**Comment by jenbreese** [comment]
Ok. I'm taking a look.

**Comment by jenbreese** [comment]
@pookmish Do you have a recommendation for a better way to get the wider card width?

**Comment by pookmish** [comment]
> @pookmish Do you have a recommendation for a better way to get the wider card width?

@jenbreese Reducing the number per row. that's the only option.

**Comment by jenbreese** [comment]
Want me to commit the compiled css?

**Review by jdwjdwjdw — APPROVED** [review]
Thanks for your help getting the template to work @pookmish. It looks like changing the width fixed some of the related issues I was seeing during my Chem-H visual regression testing as well. I noticed some additional funkiness with the cards which I will address in a separate PR.

**Pull request merged**
