### PR TITLE
CHEMH-89 | @jdwjdwjdw | Style event node and teaser

### PR DESCRIPTION
**Pull request by jdwjdwjdw**
# READY FOR REVIEW

# Summary
- See Events node page and teasers in [figma](https://www.figma.com/file/wq9Y5igro1BLYN0kbeojC7/ChEM-H-Design-02?type=design&node-id=201-281&mode=design&t=RhPnuFwhNv33ctJ9-0)
- [CHEMH-89](https://stanfordits.atlassian.net/browse/CHEMH-89): Style event node
  - I wasn't able to match designs completely due to drupal/subtheme limitations, but got as close as I could.
- [CHEMH-86](https://stanfordits.atlassian.net/browse/CHEMH-86): Card display in teaser
- [CHEMH-87](https://stanfordits.atlassian.net/browse/CHEMH-87): Card display in More Events
- [CHEMH-85](https://stanfordits.atlassian.net/browse/CHEMH-85): Card display in grid
- Fixup event cta button icon bug

# Review By (Date)
- When convenient

# Urgency
- Normal

# Review Tasks

## Setup tasks and/or behavior to test

1. Check out this branch
2. Add some example events
3. Confirm that the event node page matches figma (outside of limitations with field order/display)
4. Confirm that the more events cards match the designs
5. Add a basic page with events lists and teasers, and confirm that they match the designs
6. Review code 🥗 

# Associated Issues and/or People
- [CHEMH-89](https://stanfordits.atlassian.net/browse/CHEMH-89): Style event node

[CHEMH-89]: https://stanfordits.atlassian.net/browse/CHEMH-89?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CHEMH-89]: https://stanfordits.atlassian.net/browse/CHEMH-89?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CHEMH-86]: https://stanfordits.atlassian.net/browse/CHEMH-86?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CHEMH-87]: https://stanfordits.atlassian.net/browse/CHEMH-87?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CHEMH-85]: https://stanfordits.atlassian.net/browse/CHEMH-85?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by jenbreese** [comment]
@jdwjdwjdw I started looking at it. In the phone views, the headings and related topics seem really big.
Screenshot 2023-09-22 at 10 31 35 AM
Screenshot 2023-09-22 at 10 31 12 AM

**Comment by jenbreese** [comment]
The cards might need to be left aligned instead of spaced out. This is a set of 5 teasers. 
Screenshot 2023-09-22 at 11 17 45 AM

Here is a list of events in a card grid and they have the display I was thinking of. 
Screenshot 2023-09-22 at 11 22 07 AM

**Comment by jdwjdwjdw** [comment]
> @jdwjdwjdw I started looking at it. In the phone views, the headings and related topics seem really big. Screenshot 2023-09-22 at 10 31 35 AM Screenshot 2023-09-22 at 10 31 12 AM

Thanks Jen! It looks like all of our headings have a fixed rem font-size currently (see https://github.com/SU-SWS/chem_h_subtheme/blob/67c2d8c202eccae016d9cb588e09d686c503bea5/src/scss/theme/_headings.scss#L16), so that's why they appear really big on mobile. What do you think we should do - update those heading font-sizes to use one of the decanter type sizes, or just add some additional smaller rem font sizes for smaller breakpoints on all of the headings?

> The cards might need to be left aligned instead of spaced out. This is a set of 5 teasers. Screenshot 2023-09-22 at 11 17 45 AM
> 
> Here is a list of events in a card grid and they have the display I was thinking of. Screenshot 2023-09-22 at 11 22 07 AM

It looks like the difference between the card gaps for lists and teasers is due to lists using CSS Grid, and teasers using Flexbox, which matches what's currently on Stanford Basic (see https://amptesting.sites.stanford.edu/sws-test-922-events-lists-teasers). I'm not sure how much work it would take to change that, but is probably something that should be done on Stanford Basic is we do decide to update that.

**Comment by jenbreese** [comment]
@jdwjdwjdw I think we update to the Decanter typography.

**Review by jenbreese — APPROVED** [review]
I tried it this morning and the fonts are much better. I agree about the card layout coming from SB instead of just fixing here.

**Pull request merged**
